name = "SFRM"
uuid = "a1f4a418-2db2-426e-8f95-4f1e101cdea5"
authors = ["Artem m410y@proton.me"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
