const LINE_LEN = 80
const BLOCK_SIZE = 512
const BLOCKS_MIN = 5
const KEY_LEN = 8
const DATA_ALIGNMENT = 16
const HEADER_FIELDS = ImmutableDict(
    "FORMAT" => (Int,),
    "VERSION" => (Int,),
    "HDRBLKS" => (Int,),
    # "SITE"      => (String,),
    # "MODEL"     => (String,),
    # "USER"      => (String,),
    # "SAMPLE"    => (String,),
    # "SETNAME"   => (String,),
    "RUN" => (Int,),
    "SAMPNUM" => (Int,),
    # "TITLE"     => (String,),
    "NCOUNTS" => (Int, Int),
    "NOVERFL" => (Int, Int, Int),
    "MINIMUM" => (Int,),
    "MAXIMUM" => (Int,),
    "NONTIME" => (Int,),
    "NLATE" => (Int,),
    # "FILENAM"   => (String,),
    "CREATED" => (String, String),
    "CUMULAT" => (Float64,),
    "ELAPSDR" => (Float64,),
    "ELAPSDA" => (Float64,),
    "OSCILLA" => (Int,),
    "NSTEPS" => (Int,),
    "RANGE" => (Float64,),
    "START" => (Float64,),
    "INCREME" => (Float64,),
    "NUMBER" => (Int,),
    "NFRAMES" => (Int,),
    "ANGLES" => (Float64, Float64, Float64, Float64),
    "NOVER64" => (Int, Int, Int),
    "NPIXELB" => (Int, Int),
    "NROWS" => (Int, Int),
    "NCOLS" => (Int, Int),
    "WORDORD" => (Int,),
    "LONGORD" => (Int,),
    # "TARGET"    => (String,),
    "SOURCEK" => (Float64,),
    "SOURCEM" => (Float64,),
    # "FILTER"    => (String,),
    "CELL" => (Float64, Float64, Float64, Float64, Float64, Float64),
    "MATRIX" => (
        Float64,
        Float64,
        Float64,
        Float64,
        Float64,
        Float64,
        Float64,
        Float64,
        Float64,
    ),
    "LOWTEMP" => (Int, Int, Int, String, Float64, Float64, Int),
    "ZOOM" => (Float64, Float64, Float64),
    "CENTER" => (Float64, Float64, Float64, Float64),
    "DISTANC" => (Float64, Float64),
    "TRAILER" => (Int,),
    "COMPRES" => (Int,),
    "LINEAR" => (Float64, Float64),
    "PHD" => (Float64, Float64),
    "PREAMP" => (Float64,),
    # "CORRECT"   => (String,),
    # "WARPFIL"   => (String,),
    "WAVELEN" => (Float64, Float64, Float64, Float64),
    "MAXXY" => (Float64,),
    "AXIS" => (Int,),
    "ENDING" => (Float64, Float64, Float64, Float64),
    "DETPAR" => (Float64, Float64, Float64, Float64, Float64, Float64),
    # "LUT"       => (String,),
    "DISPLIM" => (Float64, Float64),
    # "PROGRAM"   => (String,),
    "ROTATE" => (Int,),
    # "BITMASK"   => (String,),
    "OCTMASK" =>
        (Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64),
    "ESDCELL" => (Float64, Float64, Float64, Float64, Float64, Float64),
    "DETTYPE" => (String, Float64, Float64, Int, Float64, Float64),
    "NEXP" => (Int, Int, Int, Int, Int),
    "CCDPARM" => (Float64, Float64, Float64, Float64, Float64),
    # "CHEM"      => (String,),
    # "MORPH"     => (String,),
    # "CCOLOR"    => (String,),
    # "CSIZE"     => (String,),
    # "DNSMET"    => (String,),
    # "DARK"      => (String,),
    "AUTORNG" => (Float64, Float64, Float64, Float64, Float64),
    "ZEROADJ" => (Float64, Float64, Float64, Float64),
    "XTRANS" => (Float64, Float64, Float64),
    "HKL&XY" => (Float64, Float64, Float64, Float64, Float64),
    "AXES2" => (Float64, Float64, Float64, Float64),
    "ENDING2" => (Float64, Float64, Float64, Float64),
    "FILTER2" => (Float64, Float64, Float64, Float64),
    # "LEPTOS"    => (String,),
)
const HEADER_OREDER = String[
    "FORMAT",
    "VERSION",
    "HDRBLKS",
    "SITE",
    "MODEL",
    "USER",
    "SAMPLE",
    "SETNAME",
    "RUN",
    "SAMPNUM",
    "TITLE",
    "NCOUNTS",
    "NOVERFL",
    "MINIMUM",
    "MAXIMUM",
    "NONTIME",
    "NLATE",
    "FILENAM",
    "CREATED",
    "CUMULAT",
    "ELAPSDR",
    "ELAPSDA",
    "OSCILLA",
    "NSTEPS",
    "RANGE",
    "START",
    "INCREME",
    "NUMBER",
    "NFRAMES",
    "ANGLES",
    "NOVER64",
    "NPIXELB",
    "NROWS",
    "NCOLS",
    "WORDORD",
    "LONGORD",
    "TARGET",
    "SOURCEK",
    "SOURCEM",
    "FILTER",
    "CELL",
    "MATRIX",
    "LOWTEMP",
    "ZOOM",
    "CENTER",
    "DISTANC",
    "TRAILER",
    "COMPRES",
    "LINEAR",
    "PHD",
    "PREAMP",
    "CORRECT",
    "WARPFIL",
    "WAVELEN",
    "MAXXY",
    "AXIS",
    "ENDING",
    "DETPAR",
    "LUT",
    "DISPLIM",
    "PROGRAM",
    "ROTATE",
    "BITMASK",
    "OCTMASK",
    "ESDCELL",
    "DETTYPE",
    "NEXP",
    "CCDPARM",
    "CHEM",
    "MORPH",
    "CCOLOR",
    "CSIZE",
    "DNSMET",
    "DARK",
    "AUTORNG",
    "ZEROADJ",
    "XTRANS",
    "HKL&XY",
    "AXES2",
    "ENDING2",
    "FILTER2",
    "LEPTOS",
]